#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'optparse'
require_relative '../lib/agent_workflows/github'
require_relative '../lib/agent_workflows/merge'
require_relative '../lib/agent_workflows/usage'
require_relative '../lib/agent_workflows/work'

if ARGV.first == 'usage'
  ARGV.shift
  exit AgentWorkflows::Usage.run(ARGV)
end

if ARGV.first == 'work'
  ARGV.shift
  exit AgentWorkflows::Work.run(ARGV)
end

options = {}
parser = OptionParser.new do |flags|
  flags.banner = 'Usage: sw (pr|walkthrough|merge) OWNER/REPO NUMBER [options]; sw usage --help; sw work --help'
  flags.on('--head SHA', 'Expected current PR head') { |value| options[:head] = value }
  flags.on('--body-file PATH', 'Walkthrough Markdown file') { |value| options[:body_file] = value }
  flags.on('--walkthrough ID', 'Published COMMENT review ID') { |value| options[:walkthrough] = value }
  flags.on('-h', '--help', 'Show usage') do
    puts flags
    exit
  end
end

begin
  parser.parse!(ARGV)
  command, repository, number = ARGV
  raise OptionParser::InvalidArgument, parser.to_s unless ARGV.length == 3 && %w[pr walkthrough merge].include?(command)

  github = AgentWorkflows::GitHub.new(repository, number)
  result = case command
           when 'pr' then github.snapshot
           when 'walkthrough'
             github.walkthrough(head: options.fetch(:head),
                                body: File.read(options.fetch(:body_file), encoding: 'UTF-8'))
           when 'merge'
             AgentWorkflows::Merge.new(github).call(head: options.fetch(:head),
                                                    walkthrough: options.fetch(:walkthrough))
           end
  puts JSON.pretty_generate(result)
rescue OptionParser::ParseError, KeyError, SystemCallError, AgentWorkflows::Error => e
  warn "sw: #{e.message}"
  exit 1
end
